apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: logviewer-dev
  labels:
    app: database
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        tier: data
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: database
        image: logviewer-dev/database:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "50m"
            memory: "32Mi"
          limits:
            cpu: "200m"
            memory: "64Mi"
