apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: logviewer-dev
  labels:
    app: scheduler
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
        tier: backend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: scheduler
        image: logviewer-dev/scheduler:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "50m"
            memory: "32Mi"
          limits:
            cpu: "200m"
            memory: "64Mi"
