apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: logviewer-dev
  labels:
    app: user-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        tier: backend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: user-service
        image: logviewer-dev/user-service:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "50m"
            memory: "32Mi"
          limits:
            cpu: "200m"
            memory: "64Mi"
